apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-conf
  labels:
    app: influxdb
data:
  influxdb.conf: |
    bind-adress="127.0.0.1:8088"
    [meta]
      dir="/var/lib/influxdb/meta"
    [data]
      dir="/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      trace-logging-enable=true
    [http]
      bind-addres=":8086"
      log-enabled=true
    [[graphite]]
      database="telegraf"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 5
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb-container
          image: influxdb-img
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-volume
              mountPath: /var/lib/influxdb
            - name: influxdb-conf
              mountPath: /etc/influxdb/influxdb.conf
              subPath: influxdb.conf
              readOnly: true
          envFrom:
            - secretRef:
                name: influxdb-secret
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-pvc
        - name: influxdb-conf
          configMap:
            name: influxdb-conf
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  labels:
    app: influxdb
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: admin
  INFLUXDB_DB: telegraf
  INFLUXDB_USER: user
  INFLUXDB_USER_PASSWORD: user
