FROM alpine:latest

#ARG MINIKUBE_IP

VOLUME [ "/var/lib/mysql" ]

# packages
RUN apk update \
&& apk add mariadb mariadb-client \
&& apk add --no-cache --upgrade bash \
&& apk add openrc --no-cache

RUN 	mkdir -p /run/mysqld

# Copy initialisation scripts
COPY ./start.sh .
COPY ./setup_db.cnf .
#COPY ./wordpress.sql .
COPY ./my.cnf /etc/mysql/

#RUN sed -i "s/MINIKUBE_IP/$MINIKUBE_IP/g" ./wordpress.sql

# Add permissions
RUN chmod +x ./start.sh
RUN chmod +x /etc/mysql/my.cnf

EXPOSE 3306
ENTRYPOINT [ "sh", "./start.sh" ]
