
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysqlapp
spec:
  ports:
    - port: 3306
  selector:
    app: mysqlapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysqlapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysqlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlapp
  template:
    metadata:
      labels:
        app: mysqlapp
    spec:
      containers:
        - image: mysql-img
          name: mysql
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
