apiVersion: 1
datasources:
- name: InfluxDB
  type: influxdb
  # orgId: 1
  url: http://influxdb-service:8086
  database: telegraf
  user: telegraf
  password: metricsmetricsmetricsmertics
  # version: 1
  editable: false
  # basicAuth: true
  # basicAuthUser: admin
  # basicAuthPassword: admin
