apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx-img
        name: nginx-container
        imagePullPolicy: Never
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 22
        resources: {}
status: {}
---
    apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
      name: nginx-service
    spec:
      ports:
      - port: 80
        name: http
        protocol: TCP
        targetPort: 80
      - port: 22
        name: ssh
        protocol: TCP
        targetPort: 22
      - port: 443
        name: https
        protocol: TCP
        targetPort: 443
      selector:
        app: nginx
      type: LoadBalancer
      loadBalancerIP: 192.168.99.241
    status:
      loadBalancer: {}
