apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadminapp
spec:
  selector:
    app: phpmyadminapp
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  ports:
    - port: 5000
      name: port
      targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadminapp
spec:
  selector:
    matchLabels:
      app: phpmyadminapp
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadminapp
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin-img
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
