apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.195
  ports:
    - port: 5050
      name: port
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress-container
          image: wordpress-img
          imagePullPolicy: Never
          ports:
            - containerPort: 5050