apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpressapp
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - port: 5050
      name: port
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpressapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpressapp
  template:
    metadata:
      labels:
        app: wordpressapp
      name: wordpress-pod
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        ports:
        - containerPort: 5050
        imagePullPolicy: Never
        env:
          - name: DB_NAME
            value: wordpress
          - name: DB_USER
            value: ttamesha
          - name: DB_PASSWORD
            value: admin
          - name: DB_HOST
            value: mysql
