apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secret
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://influxdb-service:8086
  INFLUXDB_USER: admin
  INFLUXDB_PASSWORD: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-conf
data:
  telegraf.conf: |
    [global_tags]
    [agent]
    interval = "10s"
    round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = true
    ###############################################################################
    #                            OUTPUT PLUGINS                                   #
    ###############################################################################
    [[outputs.influxdb]]
      urls = ["$INFLUXDB_URL"]
      database = "$INFLUXDB_DB"
      username = "$INFLUXDB_USER"
      password = "$INFLUXDB_USER_PASSWORD"
    ###############################################################################
    #                            INPUT PLUGINS                                    #
    ###############################################################################
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_name_include = []
      perdevice = true
      tag_env = ["JAVA_HOME", "HEAP_SIZE"]
      total = true
      docker_label_include = []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      name: telegraf-pod
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf-container
          image: telegraf-img
          imagePullPolicy: Never
          volumeMounts:
            - name: telegraf-conf
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock #in docker container
          envFrom:
            - secretRef:
                name: telegraf-secret
      volumes:
        - name: telegraf-conf
          configMap:
            name: telegraf-conf
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock #in VM cluster
            type: Socket
